Repository lawnstarter/react-native-picker-select, pull requests merged in 2024-08, with the labels that each got.

#609 feat: apply custom styling to active dropdown item
  index.d.ts
  src/index.js
  test/test.js
Labels: enhancement

#611 build(release): release 9.3.0
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#605 fix(types): add prop testID to `index.d.ts`
  index.d.ts
Labels: bug

#612 build(release): release 9.3.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending
